package org.harvestcircle.buildlogic.contracts

public data class DesktopBuildMetadataValues(
    val productVersion: String,
    val distributionPackageVersion: String,
    val gradleToolchain: String,
    val javaToolchain: String,
    val kotlinToolchain: String,
    val composeMultiplatformVersion: String,
)

public object GeneratedKotlin {
    public fun desktopBuildMetadata(values: DesktopBuildMetadataValues): String =
        """
        |// @generated by the HarvestCircle Gradle build. Do not edit.
        |package org.harvestcircle.application.generated
        |
        |internal object DesktopBuildMetadata {
        |    const val productVersion = ${values.productVersion.quoted()}
        |    const val distributionPackageVersion = ${values.distributionPackageVersion.quoted()}
        |    const val gradleToolchain = ${values.gradleToolchain.quoted()}
        |    const val javaToolchain = ${values.javaToolchain.quoted()}
        |    const val kotlinToolchain = ${values.kotlinToolchain.quoted()}
        |    const val composeMultiplatformVersion = ${values.composeMultiplatformVersion.quoted()}
        |}
        """.trimMargin() + "\n"

    public fun compatibilityExpectations(baseline: FfiCompatibilityBaseline): String =
        """
        |// @generated by the HarvestCircle Gradle build. Do not edit.
        |package org.harvestcircle.application.generated
        |
        |internal object NativeCompatibilityExpectations {
        |    const val ffiContractId = ${baseline["contract.id"].quoted()}
        |    const val productVersion = ${baseline["product.version"].quoted()}
        |    const val cargoPackageVersion = ${baseline["product.version"].quoted()}
        |    const val distributionPackageVersion = ${baseline["package.version"].quoted()}
        |    const val productCoordinateDigest = ${baseline["product.coordinate_digest"].quoted()}
        |    const val sourceProvenanceDigest = ${baseline["source.provenance_digest"].quoted()}
        |    const val sourceFoundationBaseline = ${baseline["source.foundation_baseline"].quoted()}
        |    const val ffiContractHash = ${baseline["contract.hash"].quoted()}
        |    val ffiContractMajor: UShort = ${baseline["contract.major"]}.toUShort()
        |    val minimumFfiContractMinor: UShort = ${baseline["contract.minor"]}.toUShort()
        |    const val snapshotSchema: UInt = ${baseline["snapshot.schema"]}U
        |    const val minimumStorageSchema: UInt = ${baseline["storage.schema.minimum"]}U
        |    const val maximumStorageSchema: UInt = ${baseline["storage.schema.current"]}U
        |}
        """.trimMargin() + "\n"

    public fun requireFresh(
        actual: String?,
        expected: String,
        label: String,
    ) {
        require(actual != null) { "$label is missing" }
        require(actual == expected) { "$label is stale" }
    }
}

private fun String.quoted(): String =
    buildString {
        append('"')
        this@quoted.forEach { character ->
            when (character) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(character)
            }
        }
        append('"')
    }
