[package]
name = "harvestcircle_xtask"
version = "0.1.0-alpha"
edition = "2024"
rust-version = "1.97.1"
license = "GPL-3.0-only"
publish = false

[workspace]

[dependencies]
libc = "0.2.189"
sha2 = "0.10.9"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
