package org.harvestcircle.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

object CompatibilityExpectationsSource {
    fun render(baseline: FfiCompatibilityBaseline): String =
        """
        |// @generated by the HarvestCircle Gradle build. Do not edit.
        |package org.harvestcircle.application.generated
        |
        |internal object NativeCompatibilityExpectations {
        |    const val ffiContractId = ${baseline["contract.id"].quoted()}
        |    const val productVersion = ${baseline["product.version"].quoted()}
        |    const val cargoPackageVersion = ${baseline["product.version"].quoted()}
        |    const val distributionPackageVersion = ${baseline["package.version"].quoted()}
        |    const val productCoordinateDigest = ${baseline["product.coordinate_digest"].quoted()}
        |    const val sourceProvenanceDigest = ${baseline["source.provenance_digest"].quoted()}
        |    const val sourceFoundationBaseline = ${baseline["source.foundation_baseline"].quoted()}
        |    const val ffiContractHash = ${baseline["contract.hash"].quoted()}
        |    val ffiContractMajor: UShort = ${baseline.ushort("contract.major")}.toUShort()
        |    val minimumFfiContractMinor: UShort = ${baseline.ushort("contract.minor")}.toUShort()
        |    const val snapshotSchema: UInt = ${baseline.uint("snapshot.schema")}U
        |    const val minimumStorageSchema: UInt = ${baseline.uint("storage.schema.minimum")}U
        |    const val maximumStorageSchema: UInt = ${baseline.uint("storage.schema.current")}U
        |}
        """.trimMargin() + "\n"

    fun requireFresh(
        actual: String?,
        expected: String,
    ) {
        require(actual != null) { "Generated Kotlin compatibility expectations are missing" }
        require(actual == expected) { "Generated Kotlin compatibility expectations are stale" }
    }

    private fun String.quoted(): String =
        buildString {
            append('"')
            this@quoted.forEach { character ->
                when (character) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(character)
                }
            }
            append('"')
        }

    private fun FfiCompatibilityBaseline.uint(key: String): UInt =
        this[key].toUIntOrNull() ?: error("FFI baseline $key must be an unsigned integer")

    private fun FfiCompatibilityBaseline.ushort(key: String): UShort =
        this[key].toUShortOrNull() ?: error("FFI baseline $key must fit an unsigned short")
}

abstract class GenerateCompatibilityExpectations : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val baselineFile: RegularFileProperty

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val source = CompatibilityExpectationsSource.render(FfiCompatibilityBaseline.load(baselineFile.get().asFile))
        val output = outputFile.get().asFile
        output.parentFile.mkdirs()
        output.writeText(source)
    }
}

abstract class VerifyGeneratedCompatibilityExpectations : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val baselineFile: RegularFileProperty

    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val generatedFile: RegularFileProperty

    @TaskAction
    fun verify() {
        val expected = CompatibilityExpectationsSource.render(FfiCompatibilityBaseline.load(baselineFile.get().asFile))
        check(runCatching { CompatibilityExpectationsSource.requireFresh(null, expected) }.isFailure)
        check(runCatching { CompatibilityExpectationsSource.requireFresh("$expected// stale\n", expected) }.isFailure)
        CompatibilityExpectationsSource.requireFresh(generatedFile.get().asFile.readText(), expected)
    }
}
