package org.harvestcircle.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

data class DesktopBuildMetadataValues(
    val productVersion: String,
    val distributionPackageVersion: String,
    val gradleToolchain: String,
    val javaToolchain: String,
    val kotlinToolchain: String,
    val composeMultiplatformVersion: String,
)

object DesktopBuildMetadataSource {
    fun render(values: DesktopBuildMetadataValues): String =
        """
        |// @generated by the HarvestCircle Gradle build. Do not edit.
        |package org.harvestcircle.application.generated
        |
        |internal object DesktopBuildMetadata {
        |    const val productVersion = ${values.productVersion.quoted()}
        |    const val distributionPackageVersion = ${values.distributionPackageVersion.quoted()}
        |    const val gradleToolchain = ${values.gradleToolchain.quoted()}
        |    const val javaToolchain = ${values.javaToolchain.quoted()}
        |    const val kotlinToolchain = ${values.kotlinToolchain.quoted()}
        |    const val composeMultiplatformVersion = ${values.composeMultiplatformVersion.quoted()}
        |}
        """.trimMargin() + "\n"

    fun requireFresh(
        actual: String?,
        expected: String,
    ) {
        require(actual != null) { "Generated desktop build metadata is missing" }
        require(actual == expected) { "Generated desktop build metadata is stale" }
    }

    private fun String.quoted(): String =
        buildString {
            append('"')
            this@quoted.forEach { character ->
                when (character) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(character)
                }
            }
            append('"')
        }
}

abstract class DesktopBuildMetadataTask : DefaultTask() {
    @get:Input
    abstract val productVersion: Property<String>

    @get:Input
    abstract val distributionPackageVersion: Property<String>

    @get:Input
    abstract val gradleToolchain: Property<String>

    @get:Input
    abstract val javaToolchain: Property<String>

    @get:Input
    abstract val kotlinToolchain: Property<String>

    @get:Input
    abstract val composeMultiplatformVersion: Property<String>

    protected fun values(): DesktopBuildMetadataValues =
        DesktopBuildMetadataValues(
            productVersion = productVersion.get(),
            distributionPackageVersion = distributionPackageVersion.get(),
            gradleToolchain = gradleToolchain.get(),
            javaToolchain = javaToolchain.get(),
            kotlinToolchain = kotlinToolchain.get(),
            composeMultiplatformVersion = composeMultiplatformVersion.get(),
        )
}

abstract class GenerateDesktopBuildMetadata : DesktopBuildMetadataTask() {
    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val output = outputFile.get().asFile
        output.parentFile.mkdirs()
        output.writeText(DesktopBuildMetadataSource.render(values()))
    }
}

abstract class VerifyGeneratedDesktopBuildMetadata : DesktopBuildMetadataTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val generatedFile: RegularFileProperty

    @TaskAction
    fun verify() {
        val expected = DesktopBuildMetadataSource.render(values())
        check(runCatching { DesktopBuildMetadataSource.requireFresh(null, expected) }.isFailure)
        check(runCatching { DesktopBuildMetadataSource.requireFresh("$expected// stale\n", expected) }.isFailure)
        DesktopBuildMetadataSource.requireFresh(generatedFile.get().asFile.readText(), expected)
    }
}
