config:
  validation: true
  warningsAsErrors: true

complexity:
  CyclomaticComplexMethod:
    allowedComplexity: 20
  LongMethod:
    allowedLines: 80
  TooManyFunctions:
    allowedFunctionsPerClass: 30

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'

style:
  ReturnCount:
    max: 4
    excludeGuardClauses: true
