use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use sha2::{Digest, Sha256};

#[path = "src/parser.rs"]
mod parser;

use parser::{REQUIRED, parse};

const MANIFEST_PATH: &str = "../../../config/product/harvestcircle-v1.properties";
fn main() {
    println!("cargo:rerun-if-changed={MANIFEST_PATH}");
    let source = fs::read_to_string(MANIFEST_PATH).expect("read HarvestCircle product manifest");
    let coordinates = parse(&source).expect("validate HarvestCircle product manifest");
    let digest = Sha256::digest(source.as_bytes())
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();

    let mut generated = String::from("// @generated by harvestcircle_product/build.rs\n");
    for (key, _) in REQUIRED {
        let constant = key.replace(['.', '-'], "_").to_ascii_uppercase();
        writeln!(
            generated,
            "pub const {constant}: &str = {:?};",
            coordinates.get(*key).expect("required coordinate")
        )
        .expect("write coordinate constant");
    }
    writeln!(
        generated,
        "pub const PRODUCT_COORDINATE_DIGEST: &str = {digest:?};"
    )
    .expect("write coordinate digest");
    writeln!(
        generated,
        "pub const DEVELOPMENT_DATA_DIR_ENVIRONMENT: &str = {:?};",
        format!(
            "{}DEVELOPMENT_DATA_DIR",
            coordinates
                .get("environment.prefix")
                .expect("environment prefix")
        )
    )
    .expect("write derived development environment coordinate");

    fs::write(out_file("product_coordinates.rs"), generated)
        .expect("write generated product coordinates");
}

fn out_file(name: &str) -> PathBuf {
    PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR")).join(name)
}
