pub const FFI_CONTRACT_ID: &str = env!("HARVESTCIRCLE_FFI_CONTRACT_ID");
pub const PRODUCT_VERSION: &str = env!("HARVESTCIRCLE_PRODUCT_VERSION");
pub const DISTRIBUTION_PACKAGE_VERSION: &str = env!("HARVESTCIRCLE_PACKAGE_VERSION");
pub const FFI_CONTRACT_MAJOR: u16 = 4;
pub const FFI_CONTRACT_MINOR: u16 = 0;
pub const PRODUCT_COORDINATE_DIGEST: &str = env!("HARVESTCIRCLE_PRODUCT_COORDINATE_DIGEST");
pub const SNAPSHOT_SCHEMA_VERSION: u32 = 1;
pub const MINIMUM_SCHEMA_VERSION: u32 = 5;
pub const SOURCE_PROVENANCE_DIGEST: &str = env!("HARVESTCIRCLE_SOURCE_PROVENANCE_DIGEST");
pub const SOURCE_FOUNDATION_BASELINE: &str = env!("HARVESTCIRCLE_SOURCE_FOUNDATION_BASELINE");
pub const FFI_CONTRACT_HASH: &str = env!("HARVESTCIRCLE_FFI_CONTRACT_DIGEST");

#[cfg(test)]
pub(crate) const NORMALIZED_CONTRACT_METADATA: &str =
    include_str!(concat!(env!("OUT_DIR"), "/ffi_contract_metadata.txt"));
