use std::collections::BTreeMap;

use sha2::{Digest, Sha256};

pub const SCHEMA: &str = "harvestcircle.product.v1";
pub const REQUIRED_KEYS: &[&str] = &[
    "schema",
    "product.name",
    "product.slug",
    "kotlin.root_namespace",
    "desktop.application_id",
    "desktop.bundle_id",
    "desktop.main_class",
    "ffi.kotlin_package",
    "ffi.cdylib_name",
    "database.qualifier",
    "database.organization",
    "database.application",
    "database.filename",
    "keyring.service",
    "environment.prefix",
    "vendor.name",
    "copyright.notice",
];

pub fn parse(source: &str) -> Result<BTreeMap<String, String>, String> {
    if source.starts_with('\u{feff}') {
        return Err("product coordinates must not contain a UTF-8 BOM".to_owned());
    }
    let mut parsed = BTreeMap::new();
    for (index, raw) in source.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .ok_or_else(|| format!("line {} is not key=value", index + 1))?;
        let key = key.trim();
        let value = value.trim();
        if key.is_empty()
            || value.is_empty()
            || key.chars().any(char::is_control)
            || value.chars().any(char::is_control)
        {
            return Err(format!("line {} has an invalid key or value", index + 1));
        }
        if !REQUIRED_KEYS.contains(&key) {
            return Err(format!("unknown coordinate {key}"));
        }
        if parsed.insert(key.to_owned(), value.to_owned()).is_some() {
            return Err(format!("duplicate coordinate {key}"));
        }
    }
    for key in REQUIRED_KEYS {
        let value = parsed
            .get(*key)
            .ok_or_else(|| format!("missing coordinate {key}"))?;
        validate_coordinate(key, value)?;
    }
    Ok(parsed)
}

pub fn canonicalize(source: &str) -> Result<String, String> {
    let parsed = parse(source)?;
    let mut canonical = String::new();
    for key in REQUIRED_KEYS {
        canonical.push_str(key);
        canonical.push('=');
        canonical.push_str(parsed.get(*key).expect("required coordinate was validated"));
        canonical.push('\n');
    }
    Ok(canonical)
}

pub fn generate_rust_constants(source: &str) -> Result<String, String> {
    use std::fmt::Write as _;

    let coordinates = parse(source)?;
    let digest = digest(source)?;
    let mut generated = String::from("// @generated by harvestcircle_product/build.rs\n");
    for key in REQUIRED_KEYS {
        let constant = key.replace(['.', '-'], "_").to_ascii_uppercase();
        writeln!(
            generated,
            "pub const {constant}: &str = {:?};",
            coordinates.get(*key).expect("required coordinate")
        )
        .map_err(|error| error.to_string())?;
    }
    writeln!(
        generated,
        "pub const PRODUCT_COORDINATE_DIGEST: &str = {digest:?};"
    )
    .map_err(|error| error.to_string())?;
    writeln!(
        generated,
        "pub const DEVELOPMENT_DATA_DIR_ENVIRONMENT: &str = {:?};",
        format!(
            "{}DEVELOPMENT_DATA_DIR",
            coordinates
                .get("environment.prefix")
                .expect("environment prefix")
        )
    )
    .map_err(|error| error.to_string())?;
    Ok(generated)
}

fn validate_coordinate(key: &str, value: &str) -> Result<(), String> {
    let valid = match key {
        "schema" => value == SCHEMA,
        "product.name" | "vendor.name" | "copyright.notice" => value.len() <= 160,
        "product.slug"
        | "ffi.cdylib_name"
        | "database.qualifier"
        | "database.organization"
        | "database.application" => is_lower_identifier(value),
        "kotlin.root_namespace"
        | "desktop.application_id"
        | "desktop.bundle_id"
        | "desktop.main_class"
        | "ffi.kotlin_package"
        | "keyring.service" => is_dotted_identifier(value),
        "database.filename" => {
            value.ends_with(".sqlite3")
                && !value.contains("..")
                && value
                    .bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
        }
        "environment.prefix" => {
            value
                .bytes()
                .next()
                .is_some_and(|byte| byte.is_ascii_uppercase())
                && value.ends_with('_')
                && value
                    .bytes()
                    .all(|byte| byte.is_ascii_uppercase() || byte.is_ascii_digit() || byte == b'_')
        }
        _ => false,
    };
    if valid {
        Ok(())
    } else {
        Err(format!("coordinate {key} has an invalid value"))
    }
}

fn is_lower_identifier(value: &str) -> bool {
    value
        .bytes()
        .next()
        .is_some_and(|byte| byte.is_ascii_lowercase())
        && value
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
}

fn is_dotted_identifier(value: &str) -> bool {
    value.split('.').all(|segment| {
        segment
            .bytes()
            .next()
            .is_some_and(|byte| byte.is_ascii_alphabetic() || byte == b'_')
            && segment
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
    })
}

pub fn digest(source: &str) -> Result<String, String> {
    let canonical = canonicalize(source)?;
    Ok(Sha256::digest(canonical.as_bytes())
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect())
}
