use std::collections::BTreeMap;

use sha2::{Digest, Sha256};

pub const SCHEMA: &str = "harvestcircle.product.v1";
pub const REQUIRED_KEYS: &[&str] = &[
    "schema",
    "product.name",
    "product.slug",
    "kotlin.root_namespace",
    "desktop.application_id",
    "desktop.bundle_id",
    "desktop.main_class",
    "ffi.kotlin_package",
    "ffi.cdylib_name",
    "storage.service_id",
    "storage.instance_id",
    "storage.database_filename",
    "storage.lock_filename",
    "storage.application_id",
    "storage.application_id_text",
    "storage.initial_schema_version",
    "legacy.database.qualifier",
    "legacy.database.organization",
    "legacy.database.application",
    "legacy.database.filename",
    "legacy.database.disposition",
    "platform.macos.architecture",
    "platform.linux.architecture",
    "limit.identities",
    "limit.unfinished_durable_operations",
    "limit.preference_value_utf8_bytes",
    "limit.relay_endpoints",
    "limit.relay_url_bytes",
    "limit.events_per_relay",
    "limit.events_total",
    "limit.observers",
    "limit.actor_mailbox",
    "limit.command_deadline_min_ms",
    "limit.command_deadline_max_ms",
    "backup.member_limit",
    "keyring.service",
    "environment.prefix",
    "vendor.name",
    "copyright.notice",
];

pub fn parse(source: &str) -> Result<BTreeMap<String, String>, String> {
    if source.starts_with('\u{feff}') {
        return Err("product coordinates must not contain a UTF-8 BOM".to_owned());
    }
    let mut parsed = BTreeMap::new();
    for (index, raw) in source.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .ok_or_else(|| format!("line {} is not key=value", index + 1))?;
        let key = key.trim();
        let value = value.trim();
        if key.is_empty()
            || value.is_empty()
            || key.chars().any(char::is_control)
            || value.chars().any(char::is_control)
        {
            return Err(format!("line {} has an invalid key or value", index + 1));
        }
        if !REQUIRED_KEYS.contains(&key) {
            return Err(format!("unknown coordinate {key}"));
        }
        if parsed.insert(key.to_owned(), value.to_owned()).is_some() {
            return Err(format!("duplicate coordinate {key}"));
        }
    }
    for key in REQUIRED_KEYS {
        let value = parsed
            .get(*key)
            .ok_or_else(|| format!("missing coordinate {key}"))?;
        validate_coordinate(key, value)?;
    }
    Ok(parsed)
}

pub fn canonicalize(source: &str) -> Result<String, String> {
    let parsed = parse(source)?;
    let mut canonical = String::new();
    for key in REQUIRED_KEYS {
        canonical.push_str(key);
        canonical.push('=');
        canonical.push_str(parsed.get(*key).expect("required coordinate was validated"));
        canonical.push('\n');
    }
    Ok(canonical)
}

pub fn generate_rust_constants(source: &str) -> Result<String, String> {
    use std::fmt::Write as _;

    let coordinates = parse(source)?;
    let digest = digest(source)?;
    let mut generated = String::from("// @generated by harvestcircle_product/build.rs\n");
    for key in REQUIRED_KEYS {
        let constant = key.replace(['.', '-'], "_").to_ascii_uppercase();
        writeln!(
            generated,
            "pub const {constant}: &str = {:?};",
            coordinates.get(*key).expect("required coordinate")
        )
        .map_err(|error| error.to_string())?;
    }
    writeln!(
        generated,
        "pub const PRODUCT_COORDINATE_DIGEST: &str = {digest:?};"
    )
    .map_err(|error| error.to_string())?;
    writeln!(
        generated,
        "pub const DEVELOPMENT_DATA_DIR_ENVIRONMENT: &str = {:?};",
        format!(
            "{}DEVELOPMENT_DATA_DIR",
            coordinates
                .get("environment.prefix")
                .expect("environment prefix")
        )
    )
    .map_err(|error| error.to_string())?;
    Ok(generated)
}

fn validate_coordinate(key: &str, value: &str) -> Result<(), String> {
    let valid = match key {
        "schema" => value == SCHEMA,
        "product.name" | "vendor.name" | "copyright.notice" => value.len() <= 160,
        "product.slug" | "ffi.cdylib_name" => is_lower_identifier(value),
        "kotlin.root_namespace"
        | "desktop.application_id"
        | "desktop.bundle_id"
        | "desktop.main_class"
        | "ffi.kotlin_package"
        | "keyring.service" => is_dotted_identifier(value),
        "storage.service_id" => value == "harvestcircle",
        "storage.instance_id" => value == "desktop",
        "storage.database_filename" => value == "state.sqlite",
        "storage.lock_filename" => value == "state.lock",
        "storage.application_id" => value == "1212371505",
        "storage.application_id_text" => value == "HCR1",
        "storage.initial_schema_version" => value == "1",
        "legacy.database.qualifier" => value == "org",
        "legacy.database.organization" => value == "harvestcircle",
        "legacy.database.application" => value == "desktop",
        "legacy.database.filename" => value == "harvestcircle.sqlite3",
        "legacy.database.disposition" => value == "untouched_and_unsupported",
        "platform.macos.architecture" => value == "aarch64",
        "platform.linux.architecture" => value == "x86_64",
        "limit.identities" => value == "256",
        "limit.unfinished_durable_operations" => value == "1024",
        "limit.preference_value_utf8_bytes" => value == "4096",
        "limit.relay_endpoints" => value == "16",
        "limit.relay_url_bytes" => value == "2048",
        "limit.events_per_relay" => value == "64",
        "limit.events_total" => value == "1024",
        "limit.observers" => value == "32",
        "limit.actor_mailbox" => value == "64",
        "limit.command_deadline_min_ms" => value == "1",
        "limit.command_deadline_max_ms" => value == "30000",
        "backup.member_limit" => value == "caller_supplied_positive",
        "environment.prefix" => {
            value
                .bytes()
                .next()
                .is_some_and(|byte| byte.is_ascii_uppercase())
                && value.ends_with('_')
                && value
                    .bytes()
                    .all(|byte| byte.is_ascii_uppercase() || byte.is_ascii_digit() || byte == b'_')
        }
        _ => false,
    };
    if valid {
        Ok(())
    } else {
        Err(format!("coordinate {key} has an invalid value"))
    }
}

fn is_lower_identifier(value: &str) -> bool {
    value
        .bytes()
        .next()
        .is_some_and(|byte| byte.is_ascii_lowercase())
        && value
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
}

fn is_dotted_identifier(value: &str) -> bool {
    value.split('.').all(|segment| {
        segment
            .bytes()
            .next()
            .is_some_and(|byte| byte.is_ascii_alphabetic() || byte == b'_')
            && segment
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
    })
}

pub fn digest(source: &str) -> Result<String, String> {
    let canonical = canonicalize(source)?;
    Ok(Sha256::digest(canonical.as_bytes())
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect())
}
